spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/iam
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
