spring:
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST:localhost}:3306/iam
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
